---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/joshiprasadp/concourse-test.git
    branch: master

jobs:
  - name: build-master
    plan:
    
    - get: source-code
      resource: git-master
      trigger: true

    - set-pipeline: self-update
      file: source-code/pipelines.yml

    - task: first-task
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        inputs:
        - name: source-code
        outputs:
        - name: output-folder
        run:
            path: find
            args: [.]
# fly -t ps set-pipeline -c mod2-pipeline-1.yml -p mod2-pipeline-1