---
resources:
- name: git-master
  type: git
  source:
    uri: https://github.com/joshiprasadp/concourse-test.git
    branch: master

jobs:
  - name: build-master
    plan:

    - get: source
      resource: git-master

    - set_pipeline: self-update
      file: source/pipelines/pipelines.yml

    - task: first-task
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        inputs:
        - name: source
        outputs:
        - name: output-folder
        run:
            path: find
            args: [.]
# fly -t ps set-pipeline -c mod2-pipeline-1.yml -p mod2-pipeline-1